steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - backend/docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - backend/docker-compose.prod.yaml
      - push

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/main-project-deploy',
        'my-backend-sha256-1=asia.gcr.io/main-project-353204/my_backend:1.1.8',
      ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
